### ISSUE TITLE
The app will work on 64bit OSs

### ISSUE THREAD

**Issue by baget** [Wargog/MakeBoot#1]
you are referring to  "C:\Windows\SysWOW64\diskpart.exe"
this only exists on 64bit OSs, on 32bit OS it exist in C:\windows\System32

also you are using the 32bit Version of diskpart, why not to use alway c:\windows\System32\diskpart.exe ?

**Comment by Wargog** [comment]
Switched to 32 bit version on all OS's, should now work on any version, but I don't have a 32 bit OS to test it
